unique_ids:
  assets:
    standard-page.html: 27XFUWKLDJ6JJB6EIBS4WIZJRVVHL7C4
    theme.css: TGA4NQEHIIHXTFQBNQOJK3U7OD4TUK3T
  forms:
    Form1: SPJVGV23W2LWYWSOHNSOHJBGHK5XUS4Y
  modules: {}
  scripts: {}
  server_modules: {}
